disabled_rules: # Disable all default rules
  - trailing_whitespace
  - line_length
  - identifier_name
  - force_try
  - comma
  - empty_enum_arguments
  - multiple_closures_with_trailing_closure
  - trailing_newline
  - todo
  - colon
  - redundant_optional_initialization
  - comment_spacing
  - opening_brace
  - vertical_whitespace
  - file_length
  - empty_parentheses_with_trailing_closure
  - leading_whitespace
  - statement_position
  - trailing_comma
  - redundant_discardable_let
  - nesting
opt_in_rules: # Empty this to disable optional rules
included:
  - Wardrobe # Keep this to specify where to look for files
excluded:
  - Pods
  - DerivedData
